version: 2.1
jobs:
  deploy:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "deploy hello world" # run the `echo` command
  destroy:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "destroy hello world" # run the `echo` command

workflows:
  version: 2

  # This workflow is pre-merge of the PR and is intended to run against the PR in both the draft and final state.
  # It can also run against any push if desirable. This behaviour can be adjusted in the CircleCI settings for this workflow.
  # Deployments to the dev environment are automatic if there are no errors.
  deploy_at2:
    jobs:
      - approve-deploy:
          type: approval
          filters:
            branches:
              only: at2
            tags:
              only: /.*/

      - deploy:
          requires: [approve-deploy]
          filters:
            branches:
              only: at2
            tags:
              only: /.*/
  destroy_at2:
    jobs:
      - approve-destroy:
          type: approval
          filters:
            branches:
              only: at2
            tags:
              only: /.*/

      - destroy:
          requires: [approve-destroy]
          filters:
            branches:
              only: at2
            tags:
              only: /.*/